default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: do_good_development

test:
  <<: *default
  database: do_good_test

production:
  <<: *default
  database: do_good_production
