development:
  sessions:
    default:
      database: do_good_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: do_good_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
